# Enable or disable debugging
debug: false

# Messages sent to players. You can use &0..&f color codes.
# All messages starting with error-* have the prefix automatically added in front.
# When rewriting messages that contain text like %d and %s make sure you keep it.
messages:
  configuration-loaded: '&6Configuration loaded.'
  error-need-player: '&cYou need to be in game for this command.'
  cmd-help: '&cThis command is missing something.'
